import { useState } from "react";
import { Modal, Stack, Text, Group, Button, Box } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconDownload } from "@tabler/icons-react";
import { exportToExcel } from "@/api";

const MONTH_NAMES = [
  "Jan",
  "Fév",
  "Mar",
  "Avr",
  "Mai",
  "Juin",
  "Juil",
  "Août",
  "Sep",
  "Oct",
  "Nov",
  "Déc",
];

interface ExportModalProps {
  opened: boolean;
  onClose: () => void;
  currentYear: number;
  currentMonth: number;
}

export default function ExportModal({
  opened,
  onClose,
  currentYear,
  currentMonth,
}: ExportModalProps) {
  // month selected for export, default to current month
  const [selectedMonths, setSelectedMonths] = useState<number[]>([
    currentMonth,
  ]);
  const [isExporting, setIsExporting] = useState(false);

  const toggleMonth = (month: number) => {
    setSelectedMonths((prev) =>
      prev.includes(month)
        ? prev.filter((m) => m !== month)
        : [...prev, month].sort((a, b) => a - b),
    );
  };

  const selectAll = () =>
    setSelectedMonths([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  const clearAll = () => setSelectedMonths([]);

  const handleExport = async () => {
    if (selectedMonths.length === 0) {
      notifications.show({
        message: "Sélectionne au moins un mois",
        color: "yellow",
      });
      return;
    }

    setIsExporting(true);
    try {
      const path = await exportToExcel(currentYear, selectedMonths);
      notifications.show({
        message: `Fichier sauvegardé ${path}`,
        color: "green",
      });
      onClose();
    } catch (err) {
      notifications.show({
        message: `Erreur export : ${err}`,
        color: "red",
      });
    } finally {
      setIsExporting(false);
    }
  };

  // name generated by backend, used for display and download
  const filename = `planning_${currentYear}.xlsx`;

  return (
    <Modal
      opened={opened}
      onClose={onClose}
      title="Exporter en Excel"
      size="sm"
      centered
    >
      <Stack gap="md">
        <Text size="sm" c="dimmed">
          Sélectionne les mois à exporter pour {currentYear}
        </Text>

        <div>
          <Group justify="space-between" mb={8}>
            <Text size="xs" fw={500} c="dimmed" tt="uppercase">
              Mois
            </Text>
            <Group gap={6}>
              <Text
                size="xs"
                c="blue"
                style={{ cursor: "pointer" }}
                onClick={selectAll}
              >
                Tout sélectionner
              </Text>
              <Text size="xs" c="dimmed">
                ·
              </Text>
              <Text
                size="xs"
                c="dimmed"
                style={{ cursor: "pointer" }}
                onClick={clearAll}
              >
                Effacer
              </Text>
            </Group>
          </Group>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, 1fr)",
              gap: 6,
            }}
          >
            {MONTH_NAMES.map((name, i) => {
              const month = i + 1;
              const isSelected = selectedMonths.includes(month);
              const isCurrent = month === currentMonth;

              return (
                <Box
                  key={month}
                  onClick={() => toggleMonth(month)}
                  style={{
                    padding: "6px 4px",
                    borderRadius: 6,
                    border: isSelected
                      ? "2px solid var(--mantine-color-blue-5)"
                      : "1px solid var(--mantine-color-dark-4)",
                    background: isSelected
                      ? "var(--mantine-color-blue-9)"
                      : "transparent",
                    textAlign: "center",
                    cursor: "pointer",
                    transition: "all 0.15s",
                    position: "relative",
                  }}
                >
                  <Text
                    size="xs"
                    fw={isSelected ? 600 : 400}
                    c={isSelected ? "blue" : "dimmed"}
                  >
                    {name}
                  </Text>
                  {/* Indicateur mois courant */}
                  {isCurrent && (
                    <div
                      style={{
                        position: "absolute",
                        top: 2,
                        right: 2,
                        width: 4,
                        height: 4,
                        borderRadius: "50%",
                        background: "var(--mantine-color-blue-5)",
                      }}
                    />
                  )}
                </Box>
              );
            })}
          </div>
        </div>

        <Box
          p="xs"
          style={{
            background: "var(--mantine-color-dark-6)",
            borderRadius: 8,
            border: "1px solid var(--mantine-color-dark-4)",
          }}
        >
          <Group gap="xs">
            <Text size="xs" style={{ fontSize: 16 }}>
              📄
            </Text>
            <div>
              <Text size="xs" fw={500}>
                {filename}
              </Text>
              <Text size="xs" c="dimmed">
                {selectedMonths.length === 0
                  ? "Aucun mois sélectionné"
                  : `${selectedMonths.map((m) => MONTH_NAMES[m - 1]).join(", ")}`}
              </Text>
            </div>
          </Group>
        </Box>

        <Group justify="flex-end">
          <Button variant="subtle" onClick={onClose}>
            Annuler
          </Button>
          <Button
            leftSection={<IconDownload size={14} />}
            onClick={handleExport}
            loading={isExporting}
            disabled={selectedMonths.length === 0}
          >
            Exporter{" "}
            {selectedMonths.length > 0 ? `${selectedMonths.length} mois` : ""}
          </Button>
        </Group>
      </Stack>
    </Modal>
  );
}
